In [42]:
import pandas as pd
import numpy as np

In [43]:
df=pd.read_csv(r"C:\Users\lenovo\Python data\Imarticus Learning\trainRF.csv")
pd.set_option('display.max_rows',500)

In [44]:
df.head(100)#  price_range IS YOUR TRAGET VARIABLE

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0             842     0          2.2         0   1       0           7    0.6   
1            1021     1          0.5         1   0       1          53    0.7   
2             563     1          0.5         1   2       1          41    0.9   
3             615     1          2.5         0   0       0          10    0.8   
4            1821     1          1.2         0  13       1          44    0.6   
5            1859     0          0.5         1   3       0          22    0.7   
6            1821     0          1.7         0   4       1          10    0.8   
7            1954     0          0.5         1   0       0          24    0.8   
8            1445     1          0.5         0   0       0          53    0.7   
9             509     1          0.6         1   2       1           9    0.1   
10            769     1          2.9         1   0       0           9    0.1   
11           1520     1          2.2         0   5       1          33    0.5   
12           1815     0          2.8         0   2       0          33    0.6   
13            803     1          2.1         0   7       0          17    1.0   
14           1866     0          0.5         0  13       1          52    0.7   
15            775     0          1.0         0   3       0          46    0.7   
16            838     0          0.5         0   1       1          13    0.1   
17            595     0          0.9         1   7       1          23    0.1   
18           1131     1          0.5         1  11       0          49    0.6   
19            682     1          0.5         0   4       0          19    1.0   
20            772     0          1.1         1  12       0          39    0.8   
21           1709     1          2.1         0   1       0          13    1.0   
22           1949     0          2.6         1   4       0          47    0.3   
23           1602     1          2.8         1   4       1          38    0.7   
24            503     0          1.2         1   5       1           8    0.4   
25            961     1          1.4         1   0       1          57    0.6   
26            519     1          1.6         1   7       1          51    0.3   
27            956     0          0.5         0   1       1          41    1.0   
28           1453     0          1.6         1  12       1          52    0.3   
29            851     0          0.5         0   3       0          21    0.4   
30           1579     1          0.5         1   0       0           5    0.2   
31           1568     1          0.5         0  16       0          33    1.0   
32           1319     1          0.9         0   3       1          41    0.9   
33           1310     1          2.2         1   0       1          51    0.6   
34            644     1          2.7         0   0       0          22    0.7   
35            725     0          1.3         1  16       0          60    0.4   
36            589     1          2.3         1   1       0          61    0.6   
37           1725     1          1.6         1   6       1           6    0.5   
38            790     0          2.0         1  16       1          11    0.3   
39            560     0          0.5         1  15       0          50    0.3   
40           1347     0          2.9         0   5       0          44    0.6   
41           1646     1          2.3         0   8       1          41    0.2   
42           1253     1          0.5         1   5       1           5    0.2   
43           1656     0          1.0         0   5       1          34    0.1   
44           1195     1          2.8         0   1       1          20    0.8   
45           1514     0          2.9         0   0       0          27    0.2   
46           1723     1          1.1         1   1       0          42    1.0   
47           1054     1          1.8         1   3       1          40    0.8   
48            578     1          2.

In [45]:
df.shape

(2000, 21)

In [46]:
df.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')

In [47]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [49]:
#sampleing

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
df_train,df_test=train_test_split(df,test_size=.2)

In [52]:
df_train_x = df_train.iloc[:,0:-1]
df_train_y = df_train.iloc[:,-1]

In [53]:
df_test_x = df_test.iloc[:,0:-1]
df_test_y = df_test.iloc[:,-1]

In [54]:
print(df_train_x.shape)
print(df_train_y.shape)
print(df_test_x.shape)
print(df_test_x.shape)

(1600, 20)
(1600,)
(400, 20)
(400, 20)


In [55]:
# how to build the algrothem
# we import some fuction from sklearn
# we created an object
# run the fit fuction (it build the model) and while run your fit fuction the in put is x,y(x train ,y train)
# we did the perdiction
# run the confustion matrix

# Apply decision tree (Gini)

In [56]:
from sklearn.tree import DecisionTreeClassifier
dt_df = DecisionTreeClassifier()

In [57]:
dt_df.fit(df_train_x,df_train_y)

DecisionTreeClassifier()

In [58]:
pred= dt_df.predict(df_test_x)
pred

array([1, 3, 3, 2, 1, 2, 2, 2, 2, 3, 2, 0, 2, 3, 0, 0, 0, 2, 1, 0, 2, 0,
       3, 2, 3, 0, 3, 0, 2, 1, 2, 3, 1, 3, 0, 2, 1, 3, 0, 2, 0, 2, 3, 1,
       0, 0, 2, 1, 2, 1, 1, 0, 2, 0, 0, 0, 1, 1, 3, 1, 0, 1, 1, 2, 3, 2,
       3, 3, 2, 3, 3, 2, 0, 1, 0, 1, 2, 0, 1, 3, 2, 2, 2, 3, 3, 0, 3, 2,
       2, 0, 0, 3, 2, 3, 0, 3, 3, 0, 1, 2, 1, 1, 0, 2, 1, 3, 3, 2, 3, 2,
       0, 1, 1, 2, 1, 3, 1, 1, 2, 1, 2, 0, 1, 2, 0, 3, 2, 2, 3, 3, 2, 2,
       0, 0, 2, 2, 2, 0, 0, 0, 2, 0, 1, 1, 1, 0, 0, 0, 1, 2, 3, 3, 2, 1,
       2, 0, 1, 0, 1, 1, 2, 2, 1, 0, 3, 1, 0, 2, 2, 3, 1, 1, 1, 2, 2, 0,
       0, 0, 2, 3, 2, 3, 0, 3, 1, 2, 1, 2, 3, 3, 2, 1, 0, 2, 2, 3, 1, 3,
       2, 1, 2, 2, 3, 1, 3, 3, 2, 0, 0, 2, 2, 0, 0, 1, 2, 3, 1, 2, 1, 0,
       1, 0, 0, 2, 0, 1, 1, 3, 1, 2, 2, 3, 3, 0, 1, 0, 2, 1, 3, 3, 0, 2,
       2, 2, 0, 1, 1, 0, 2, 2, 0, 0, 2, 1, 3, 3, 3, 0, 0, 0, 2, 3, 0, 1,
       1, 0, 2, 2, 3, 0, 1, 3, 3, 2, 1, 0, 0, 2, 1, 1, 1, 2, 3, 0, 3, 0,
       1, 2, 0, 3, 0, 3, 3, 0, 3, 2, 2, 2, 0, 0, 3,

In [59]:
pred.shape

(400,)

In [60]:
from sklearn.metrics import confusion_matrix

In [61]:
tab_df = confusion_matrix(df_test_y, pred)
tab_df # the confustion matrix is build

array([[96,  7,  0,  0],
       [ 8, 77, 15,  0],
       [ 0,  9, 87, 10],
       [ 0,  0, 10, 81]], dtype=int64)

In [62]:
from sklearn.metrics import accuracy_score

In [63]:
accuracy_score(df_test_y,pred)*100

85.25

# Apply decision tree (Entropy)

In [64]:
from sklearn.tree import DecisionTreeClassifier
dt_ctg = DecisionTreeClassifier(criterion='entropy',max_depth=5)# 'max_depth=1' it u incarease the value,
                                                                    #it will increase the performation

In [65]:
dt_ctg.fit(df_train_x,df_train_y)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [66]:
pred= dt_ctg.predict(df_test_x)

In [67]:
tab_df = confusion_matrix(df_test_y, pred)
tab_df

array([[91, 12,  0,  0],
       [ 5, 92,  3,  0],
       [ 0, 17, 68, 21],
       [ 0,  0, 10, 81]], dtype=int64)

In [68]:
from sklearn.metrics import accuracy_score

In [69]:
accuracy_score(df_test_y,pred)*100

83.0

# Apply Random Forest

In [70]:
from sklearn.ensemble import RandomForestClassifier
rfc_trf = RandomForestClassifier()

In [71]:
rfc_trf.fit(df_train_x , df_train_y)

RandomForestClassifier()

In [72]:
pred2 = rfc_trf.predict(df_test_x)

pred2

array([1, 3, 3, 3, 1, 2, 2, 2, 2, 3, 2, 0, 2, 3, 0, 0, 0, 2, 2, 0, 2, 0,
       3, 2, 3, 0, 2, 0, 2, 1, 2, 3, 2, 3, 0, 2, 1, 3, 0, 2, 0, 2, 3, 1,
       0, 0, 2, 1, 2, 1, 0, 0, 1, 0, 0, 0, 2, 1, 3, 1, 1, 1, 1, 2, 3, 3,
       2, 3, 2, 2, 3, 2, 0, 0, 0, 1, 1, 0, 0, 3, 2, 1, 1, 3, 3, 0, 3, 2,
       1, 0, 0, 3, 2, 3, 0, 3, 3, 0, 1, 2, 1, 1, 0, 3, 1, 3, 3, 3, 3, 2,
       0, 1, 1, 3, 2, 3, 1, 1, 2, 2, 1, 0, 1, 2, 0, 3, 2, 3, 3, 3, 2, 1,
       0, 0, 2, 1, 2, 0, 0, 1, 2, 0, 1, 1, 1, 0, 0, 0, 1, 3, 3, 3, 2, 1,
       2, 0, 1, 1, 1, 1, 2, 2, 1, 0, 3, 2, 0, 2, 2, 2, 2, 2, 1, 2, 2, 0,
       0, 1, 2, 3, 1, 3, 0, 3, 1, 2, 1, 3, 3, 3, 2, 1, 0, 1, 2, 3, 0, 3,
       2, 1, 2, 2, 3, 1, 2, 2, 2, 0, 0, 2, 1, 0, 0, 1, 2, 3, 1, 2, 1, 0,
       1, 0, 0, 2, 0, 1, 0, 3, 1, 2, 2, 3, 3, 0, 2, 0, 2, 2, 3, 3, 0, 3,
       2, 2, 0, 1, 0, 0, 2, 1, 0, 0, 2, 1, 2, 3, 2, 0, 0, 0, 2, 3, 0, 1,
       1, 0, 2, 2, 3, 0, 1, 2, 3, 2, 2, 0, 0, 2, 1, 1, 0, 2, 3, 0, 3, 0,
       1, 2, 1, 3, 0, 3, 3, 0, 3, 3, 2, 2, 0, 0, 3,

In [73]:
from sklearn.metrics import confusion_matrix

tab_trf2 = confusion_matrix(df_test_y , pred2) 
tab_trf2

array([[98,  5,  0,  0],
       [ 8, 79, 13,  0],
       [ 0, 13, 84,  9],
       [ 0,  0, 10, 81]], dtype=int64)

In [74]:
tab_trf2.diagonal().sum() / tab_trf2.sum()

0.855

# Apply Boruta Feature sampling

In [75]:
import pandas as pd
import numpy as np

In [76]:
df=pd.read_csv(r"C:\Users\lenovo\Python data\Imarticus Learning\trainRF.csv")
pd.set_option('display.max_rows',500)

In [77]:
df.head(100)#  price_range IS YOUR TRAGET VARIABLE

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0             842     0          2.2         0   1       0           7    0.6   
1            1021     1          0.5         1   0       1          53    0.7   
2             563     1          0.5         1   2       1          41    0.9   
3             615     1          2.5         0   0       0          10    0.8   
4            1821     1          1.2         0  13       1          44    0.6   
5            1859     0          0.5         1   3       0          22    0.7   
6            1821     0          1.7         0   4       1          10    0.8   
7            1954     0          0.5         1   0       0          24    0.8   
8            1445     1          0.5         0   0       0          53    0.7   
9             509     1          0.6         1   2       1           9    0.1   
10            769     1          2.9         1   0       0           9    0.1   
11           1520     1          2.2         0   5       1          33    0.5   
12           1815     0          2.8         0   2       0          33    0.6   
13            803     1          2.1         0   7       0          17    1.0   
14           1866     0          0.5         0  13       1          52    0.7   
15            775     0          1.0         0   3       0          46    0.7   
16            838     0          0.5         0   1       1          13    0.1   
17            595     0          0.9         1   7       1          23    0.1   
18           1131     1          0.5         1  11       0          49    0.6   
19            682     1          0.5         0   4       0          19    1.0   
20            772     0          1.1         1  12       0          39    0.8   
21           1709     1          2.1         0   1       0          13    1.0   
22           1949     0          2.6         1   4       0          47    0.3   
23           1602     1          2.8         1   4       1          38    0.7   
24            503     0          1.2         1   5       1           8    0.4   
25            961     1          1.4         1   0       1          57    0.6   
26            519     1          1.6         1   7       1          51    0.3   
27            956     0          0.5         0   1       1          41    1.0   
28           1453     0          1.6         1  12       1          52    0.3   
29            851     0          0.5         0   3       0          21    0.4   
30           1579     1          0.5         1   0       0           5    0.2   
31           1568     1          0.5         0  16       0          33    1.0   
32           1319     1          0.9         0   3       1          41    0.9   
33           1310     1          2.2         1   0       1          51    0.6   
34            644     1          2.7         0   0       0          22    0.7   
35            725     0          1.3         1  16       0          60    0.4   
36            589     1          2.3         1   1       0          61    0.6   
37           1725     1          1.6         1   6       1           6    0.5   
38            790     0          2.0         1  16       1          11    0.3   
39            560     0          0.5         1  15       0          50    0.3   
40           1347     0          2.9         0   5       0          44    0.6   
41           1646     1          2.3         0   8       1          41    0.2   
42           1253     1          0.5         1   5       1           5    0.2   
43           1656     0          1.0         0   5       1          34    0.1   
44           1195     1          2.8         0   1       1          20    0.8   
45           1514     0          2.9         0   0       0          27    0.2   
46           1723     1          1.1         1   1       0          42    1.0   
47           1054     1          1.8         1   3       1          40    0.8   
48            578     1          2.

In [78]:
df.shape

(2000, 21)

In [79]:
df.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi', 'price_range'],
      dtype='object')

In [80]:
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

# sampleing

In [82]:
df_x = df_train.iloc[:,0:-1]
df_y = df_train.iloc[:,-1]

In [83]:
df_x1 =  np.array(df_x)
df_y1 =  np.array(df_y)

In [84]:
df_x1.shape

(1600, 20)

In [85]:
df_y1.shape

(1600,)

# Apply Boruta Feature sampling

In [86]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

In [87]:
from boruta import BorutaPy # Boruta dont need sampling it is used only for only feature selection not fot prediction

In [88]:
boruta_feature_selection = BorutaPy(rf, max_iter = 50, verbose = 2)
boruta_feature_selection.fit(df_x1, df_y1)

# confirmed = it is imp
# Tentative = not decided imp or not
# Rejected = you reject

Iteration: 	1 / 50
Confirmed: 	0
Tentative: 	20
Rejected: 	0
Iteration: 	2 / 50
Confirmed: 	0
Tentative: 	20
Rejected: 	0
Iteration: 	3 / 50
Confirmed: 	0
Tentative: 	20
Rejected: 	0
Iteration: 	4 / 50
Confirmed: 	0
Tentative: 	20
Rejected: 	0
Iteration: 	5 / 50
Confirmed: 	0
Tentative: 	20
Rejected: 	0
Iteration: 	6 / 50
Confirmed: 	0
Tentative: 	20
Rejected: 	0
Iteration: 	7 / 50
Confirmed: 	0
Tentative: 	20
Rejected: 	0
Iteration: 	8 / 50
Confirmed: 	4
Tentative: 	1
Rejected: 	15
Iteration: 	9 / 50
Confirmed: 	4
Tentative: 	1
Rejected: 	15
Iteration: 	10 / 50
Confirmed: 	4
Tentative: 	1
Rejected: 	15
Iteration: 	11 / 50
Confirmed: 	4
Tentative: 	1
Rejected: 	15
Iteration: 	12 / 50
Confirmed: 	4
Tentative: 	1
Rejected: 	15
Iteration: 	13 / 50
Confirmed: 	4
Tentative: 	1
Rejected: 	15
Iteration: 	14 / 50
Confirmed: 	4
Tentative: 	1
Rejected: 	15
Iteration: 	15 / 50
Confirmed: 	4
Tentative: 	1
Rejected: 	15
Iteration: 	16 / 50
Confirmed: 	4
Tentative: 	1
Rejected: 	15
Iteration: 	17 / 

BorutaPy(estimator=RandomForestClassifier(n_estimators=1000,
                                          random_state=RandomState(MT19937) at 0x2DC26C24040),
         max_iter=50, random_state=RandomState(MT19937) at 0x2DC26C24040,
         verbose=2)

In [89]:
boruta_feature_selection.support_

array([ True, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True, False, False, False, False,
       False, False])

In [90]:
df_x.columns

Index(['battery_power', 'blue', 'clock_speed', 'dual_sim', 'fc', 'four_g',
       'int_memory', 'm_dep', 'mobile_wt', 'n_cores', 'pc', 'px_height',
       'px_width', 'ram', 'sc_h', 'sc_w', 'talk_time', 'three_g',
       'touch_screen', 'wifi'],
      dtype='object')

In [91]:
df1=pd.DataFrame()
df1['Feature_name']= df_x.columns
df1['Feature_selection']= boruta_feature_selection.support_
df1

Feature_name  Feature_selection
0   battery_power               True
1            blue              False
2     clock_speed              False
3        dual_sim              False
4              fc              False
5          four_g              False
6      int_memory              False
7           m_dep              False
8       mobile_wt              False
9         n_cores              False
10             pc              False
11      px_height               True
12       px_width               True
13            ram               True
14           sc_h              False
15           sc_w              False
16      talk_time              False
17        three_g              False
18   touch_screen              False
19           wifi              False

# Sampling

In [92]:
from sklearn.model_selection import train_test_split

In [93]:
df_train,df_test=train_test_split(df,test_size=.2)

In [94]:
df_train_x = df_train.iloc[:,[0,11,12,13]]
df_train_y = df_train.iloc[:,-1]

In [95]:
df_test_x = df_test.iloc[:,[0,11,12,13]]
df_test_y = df_test.iloc[:,-1]

In [96]:
df_test_x.columns

Index(['battery_power', 'px_height', 'px_width', 'ram'], dtype='object')

In [97]:
print(df_train_x.shape)
print(df_train_y.shape)
print(df_test_x.shape)
print(df_test_y.shape)

(1600, 4)
(1600,)
(400, 4)
(400,)


In [98]:
# how to build the algrothem
# we import some fuction from sklearn
# we created an object
# run the fit fuction (it build the model) and while run your fit fuction the in put is x,y(x train ,y train)
# we did the perdiction
# run the confustion matrix

# Apply decision tree

In [99]:
from sklearn.tree import DecisionTreeClassifier
dt_df = DecisionTreeClassifier()

In [100]:
dt_df.fit(df_train_x,df_train_y)

DecisionTreeClassifier()

In [101]:
pred= dt_df.predict(df_test_x)
pred

array([3, 3, 2, 2, 1, 3, 1, 0, 0, 0, 1, 0, 2, 1, 3, 1, 1, 3, 0, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 1, 2, 3, 2, 2, 1, 2, 1, 0, 3, 2, 1, 0, 0, 1,
       3, 3, 3, 1, 1, 0, 3, 0, 0, 1, 3, 2, 3, 2, 2, 3, 0, 3, 3, 1, 0, 0,
       0, 3, 0, 2, 1, 2, 3, 1, 1, 2, 2, 2, 3, 0, 0, 3, 0, 0, 3, 0, 0, 3,
       3, 3, 3, 2, 3, 2, 2, 3, 2, 2, 3, 1, 2, 1, 2, 1, 2, 3, 1, 1, 2, 0,
       3, 0, 2, 1, 0, 1, 1, 3, 0, 0, 1, 1, 2, 0, 1, 1, 1, 1, 3, 3, 2, 0,
       2, 0, 0, 2, 0, 3, 2, 2, 2, 0, 0, 0, 1, 2, 0, 0, 3, 2, 0, 3, 1, 2,
       3, 0, 3, 2, 2, 1, 2, 0, 2, 0, 0, 0, 1, 3, 3, 2, 2, 3, 3, 0, 2, 3,
       3, 0, 3, 3, 3, 2, 3, 1, 1, 0, 1, 0, 2, 0, 3, 0, 1, 1, 1, 1, 3, 1,
       3, 1, 1, 3, 1, 0, 0, 2, 3, 3, 3, 2, 0, 2, 0, 2, 3, 2, 2, 1, 3, 3,
       0, 1, 2, 3, 1, 3, 2, 2, 3, 2, 2, 3, 0, 0, 3, 3, 2, 1, 3, 3, 2, 3,
       2, 2, 3, 2, 1, 0, 1, 2, 3, 2, 0, 2, 0, 1, 0, 1, 2, 2, 1, 0, 0, 1,
       0, 2, 3, 1, 2, 1, 1, 2, 3, 1, 3, 3, 0, 1, 0, 1, 0, 2, 0, 2, 0, 1,
       3, 2, 2, 2, 3, 2, 2, 0, 3, 1, 3, 0, 3, 3, 1,

In [102]:
pred.shape

(400,)

In [103]:
from sklearn.metrics import confusion_matrix

In [104]:
tab_df = confusion_matrix(df_test_y, pred)
tab_df # the confustion matrix is build

array([[85, 12,  0,  0],
       [ 3, 80, 10,  0],
       [ 0,  4, 87,  9],
       [ 0,  0, 15, 95]], dtype=int64)

In [105]:
from sklearn.metrics import accuracy_score

In [106]:
accuracy_score(df_test_y,pred)*100

86.75

# DT on Entropy

In [107]:
from sklearn.tree import DecisionTreeClassifier
dt_ctg = DecisionTreeClassifier(criterion='entropy',max_depth=5)# 'max_depth=1' it u incarease the value,
                                                                    #it will increase the performation

In [108]:
dt_ctg.fit(df_train_x,df_train_y)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [109]:
pred= dt_ctg.predict(df_test_x)

In [110]:
tab_df = confusion_matrix(df_test_y, pred)
tab_df

array([[85, 12,  0,  0],
       [ 4, 81,  8,  0],
       [ 0,  8, 81, 11],
       [ 0,  0, 16, 94]], dtype=int64)

In [111]:
from sklearn.metrics import accuracy_score

In [112]:
accuracy_score(df_test_y,pred)*100

85.25

# Apply Random Forest

In [113]:
from sklearn.ensemble import RandomForestClassifier
rfc_trf = RandomForestClassifier()

In [114]:
rfc_trf.fit(df_train_x , df_train_y)

RandomForestClassifier()

In [118]:
df_train_x.shape

(1600, 4)

In [119]:
pred2 = rfc_trf.predict(df_test_x)

pred2

array([3, 3, 2, 3, 1, 3, 1, 0, 0, 0, 1, 0, 2, 1, 3, 1, 1, 3, 0, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 1, 2, 3, 2, 2, 1, 2, 1, 0, 3, 2, 1, 0, 0, 1,
       3, 3, 3, 1, 1, 0, 3, 0, 0, 1, 2, 2, 3, 2, 2, 2, 0, 3, 3, 1, 0, 0,
       0, 3, 0, 2, 1, 2, 3, 1, 2, 2, 2, 2, 3, 0, 0, 3, 0, 0, 3, 0, 0, 3,
       3, 3, 3, 2, 3, 2, 2, 3, 2, 2, 3, 1, 2, 1, 2, 1, 2, 3, 1, 1, 2, 0,
       3, 0, 2, 1, 0, 1, 1, 3, 0, 0, 1, 0, 2, 0, 1, 1, 1, 1, 3, 3, 2, 0,
       2, 0, 0, 2, 0, 3, 2, 3, 2, 0, 0, 0, 1, 2, 0, 0, 2, 2, 1, 3, 1, 3,
       3, 0, 3, 2, 2, 1, 2, 0, 3, 0, 0, 0, 1, 3, 3, 2, 2, 3, 3, 0, 2, 3,
       3, 0, 3, 3, 3, 1, 3, 1, 1, 0, 1, 0, 2, 0, 3, 0, 1, 1, 1, 1, 3, 1,
       3, 1, 1, 3, 1, 1, 0, 3, 3, 3, 3, 2, 0, 2, 1, 2, 3, 2, 2, 1, 3, 3,
       0, 1, 2, 3, 1, 3, 2, 1, 3, 2, 2, 3, 0, 0, 3, 3, 2, 1, 3, 3, 2, 3,
       2, 3, 2, 2, 1, 0, 1, 2, 3, 2, 0, 2, 0, 1, 0, 1, 2, 2, 1, 0, 0, 1,
       0, 2, 3, 1, 2, 1, 0, 2, 3, 1, 3, 3, 1, 1, 0, 1, 0, 3, 0, 3, 0, 1,
       2, 2, 2, 2, 3, 2, 2, 0, 3, 1, 3, 0, 3, 3, 1,

In [120]:
from sklearn.metrics import confusion_matrix

tab_trf2 = confusion_matrix(df_test_y , pred2) 
tab_trf2

array([[ 88,   9,   0,   0],
       [  1,  85,   7,   0],
       [  0,   2,  93,   5],
       [  0,   0,   6, 104]], dtype=int64)

In [121]:
tab_trf2.diagonal().sum() / tab_trf2.sum()

0.925